---
name: CI
'on':
  push:
    branches:
      - main

jobs:
  test:
    name: collection test
    runs-on: ubuntu-16.04


    steps:
      - name: check out
        uses: actions/checkout@v2      

      - name: set up python3
        uses: actions/setup-python@v2

      - name: install test depend
        run: pip3 install molecule docker
      
      - name: download java tar file
        run: wget https://iweb.dl.sourceforge.net/project/javajdk-8/JDK8/jdk-8u241-linux-x64.tar.gz -P /opt/

      - name: Run Molecule test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLORE: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}