---
# update allternative
- name: update-alternative for java
  community.general.alternatives:
    name: java
    path: '{{ (JAVA_HOME , "bin" , "java") | path_join }}'
    link: /usr/bin/java
    priority: 1